In [9]:
import numpy as np

word_array = ['apple', 'kiwi', 'mango']
word_dict = {'apple': 0, 'banana': 1, 'orange': 2, 'grape': 3, 'melon': 4, 'peach': 5, 'pear': 6, 'kiwi': 7, 'plum': 8, 'mango': 9}

# 创建一个全为0的矩阵
one_hot_matrix = np.zeros((len(word_array), len(word_dict)))

# 对每个单词进行one-hot编码
for i, word in enumerate(word_array):
    word_index = word_dict[word]
    one_hot_matrix[i, word_index] = 1

print(one_hot_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
import numpy as np
#下载所有英文词汇表
import nltk
# 下载并导入NLTK的词汇表
nltk.download('words')
from nltk.corpus import words
word_array = ['apple', 'kiwi', 'mango']
# 创建一个包含所有英文单词的列表
word_list = words.words()
#去重重复字符
word_list = list(set(word_list))

# 创建一个字典，将每个单词与其索引对应起来
word_dict = {word: index for index, word in enumerate(word_list)}
# 创建一个全为0的矩阵
one_hot_matrix = np.zeros((len(word_array), len(word_dict)))

# 对每个单词进行one-hot编码
for i, word in enumerate(word_array):
    word_index = word_dict[word]
    one_hot_matrix[i, word_index] = 1

print(one_hot_matrix)

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\liaomin\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


235892 235892
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
