In [18]:
#实现一个全连接层
import torch as t;
import torch.nn as nn
class Linear(nn.Module):
    def __init__(self,input_feature,out_feature):
        nn.Module.__init__(self)
        #nn.Prameter是自动算梯度的
        self.w=nn.Parameter(t.randn(input_feature,out_feature))
        self.b=nn.Parameter(t.randn(out_feature))
    def forward(self,x):
        return x.mm(self.w)+self.b
    
layer=Linear(4,1)
rtn=layer(t.randn(3,4))
rtn.backward(t.ones(rtn.size()))  # 计算梯度
print(layer.w.grad)  # 获取w的梯度
print(layer.b.grad)  # 获取b的梯度

tensor([[-1.7110],
        [-1.2377],
        [-0.2291],
        [-0.6955]])
tensor([3.])


In [23]:
#实现一个多层感知器,多层感知器（Multilayer Perceptron, MLP）的隐藏层的特征数就是神经元的个数
class MulPerceptron(nn.Module):
    def __init__(self,input_feature,hidden_feature,out_feature):
        nn.Module.__init__(self)
        self.hiddenLayer=Linear(input_feature,hidden_feature)
        self.outLayer=Linear(hidden_feature,out_feature)
    def forward(self,x):
        #隐藏层进行一次全连接得到（行，hidden_feature）数据矩阵
        hout=self.hiddenLayer(x)
        #进行relu操作
        reOut=t.relu(hout)
        #进行一次全连接后得到（行，out_feature）数据矩阵
        out=self.outLayer(reOut)
        return out;
        
mp=MulPerceptron(784,512,1)
result=mp(t.randn(200,784))
print(result)

tensor([[  -12.4170],
        [ -211.0885],
        [ -314.3124],
        [  234.5295],
        [  -74.2657],
        [ -413.3431],
        [  135.3651],
        [ -247.7416],
        [ -210.7835],
        [ -400.5256],
        [ -425.7328],
        [ -291.4088],
        [ -765.7511],
        [-1160.9725],
        [ -447.3388],
        [ -511.2890],
        [  -25.5647],
        [   16.1510],
        [ -792.5206],
        [ -403.8644],
        [  290.3611],
        [ -279.8174],
        [ -362.0346],
        [   70.0442],
        [ -538.4562],
        [ -255.3131],
        [ -273.7527],
        [ -227.2953],
        [ -442.9148],
        [  319.1536],
        [   48.4505],
        [   26.5859],
        [ -738.0776],
        [  236.8847],
        [ -329.5198],
        [    2.1988],
        [ -397.8156],
        [  -90.0620],
        [    4.5624],
        [  309.9224],
        [ -487.7955],
        [  -31.2471],
        [  291.5693],
        [  512.4156],
        [ -292.4831],
        [ 